package com.mkyong.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-04-14T18:18:26.378+07:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.mkyong.com/", name = "HelloWorld")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://ws.mkyong.com/HelloWorld/getHelloWorldAsStringRequest", output = "http://ws.mkyong.com/HelloWorld/getHelloWorldAsStringResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.mkyong.com/", partName = "return")
    public java.lang.String getHelloWorldAsString();
}
